version: "3.7"
services:
  db:
    image: "postgres:alpine"
    container_name: db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: jorge
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test